version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        JAR_FILE: build/libs/star-0.0.1-SNAPSHOT.jar
    ports:
      - "8080:8080"
    container_name: star-app
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    networks:
      - my-network

  mysql:
    image: mysql:8.4.5
    container_name: my-mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: StArFaLl
      MYSQL_DATABASE: star
    ports:
      - "3306:3306"
    networks:
      - my-network

networks:
  my-network:
    driver: bridge
