services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        JAR_FILE: build/libs/star-0.0.1-SNAPSHOT.jar
    ports:
      - "8080:8080"
    container_name: star-app
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    networks:
      - my-network

networks:
  my-network:
    driver: bridge
