INSERT INTO category (created_at, updated_at, name)
VALUES (NOW(), NOW(), 'SPOT'),
       (NOW(), NOW(), 'GENERAL'),
       (NOW(), NOW(), 'PROMOTION');

INSERT INTO member (IS_DEPRECATED, CREATED_AT, UPDATED_AT, EMAIL, ENCRYPTED_KAKAO_ACCESS_TOKEN,
                    PROFILE_IMAGE_URL, ROLE)
VALUES (0, NOW(), NOW(), 'admin@admin.com', 'ASDFASDF', null, 'USER'),
       (0, NOW(), NOW(), 'user@user.com', 'ASDFASDF', null, 'USER');

INSERT INTO TEAM (HEART_COUNT, LATITUDE, LONGITUDE, PARTICIPANT_CAPACITY, PARTICIPANT_CURRENT,
                  ZOOM_LEVEL, CREATED_AT, LEADER_ID, UPDATED_AT, VERSION, WHEN_TO_MEET, DESCRIPTION,
                  ENCRYPTED_PASSWORD, LOCATION_NAME, NAME, ROAD_ADDRESS)
VALUES (0, 37.5665, 126.9780, 10, 1, 13, NOW(), 1, NOW(), 0, '2026-05-20 12:00:00', 'test',
        null,
        'test', 'test', 'test');

INSERT INTO TEAM_MEMBER (IS_DEPRECATED, IS_BANNED, CREATED_AT, MEMBER_ID, TEAM_ID, UPDATED_AT)
VALUES (0, 0, NOW(), 1, 1, NOW()),
       (0, 0, NOW(), 2, 1, NOW());


INSERT INTO BOARD (CATEGORY_ID, COMMENT_COUNT, HEART_COUNT, LATITUDE, LONGITUDE, VIEW_COUNT,
                   ZOOM_LEVEL, CREATED_AT, MEMBER_ID, UPDATED_AT, VERSION, LOCATION_NAME,
                   ROAD_ADDRESS, TEXT, TITLE)
VALUES (1, 1, 0, 37.5665, 126.9780, 1, 13, NOW(), 1, NOW(), 0, 'test', 'test', 'test', 'test');

INSERT INTO COMMENT (DEPTH, IS_DEPRECATED, BOARD_ID, CREATED_AT, MEMBER_ID, PARRENT_COMMENT_ID,
                     ROOT_COMMENT_ID, UPDATED_AT, CONTENT)
VALUES (0, 0, 1, NOW(), 1, NULL, NULL, NOW(), 'test1')
     , (1, 0, 1, NOW(), 1, 1, 1, NOW(), 'test2')
     , (2, 0, 1, NOW(), 1, 2, 1, NOW(), 'test3');

INSERT INTO TEAM_IMAGE (SORT_ORDER, CREATED_AT, TEAM_ID, UPDATED_AT, IMAGE_URL)
VALUES (0, NOW(), 1, NOW(), 'test')
     , (1, NOW(), 1, NOW(), 'test2');

INSERT INTO TEAM_HEART (CREATED_AT, MEMBER_ID, TEAM_ID, UPDATED_AT)
VALUES (NOW(), 1, 1, NOW());

INSERT INTO BOARD_HEART (BOARD_ID, CREATED_AT, MEMBER_ID, UPDATED_AT)
VALUES (1, NOW(), 1, NOW());